-- 코드를 입력하세요
WITH RENTAL_COUNT AS(
    SELECT CAR_ID, COUNT(*) TOTAL_COUNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
),
MONTH_COUNT AS(
    SELECT MONTH(START_DATE) MONTH, CAR_ID, COUNT(*) RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY MONTH(START_DATE), CAR_ID
    )
    
SELECT M.MONTH MONTH, M.CAR_ID CAR_ID, M.RECORDS RECORDS FROM MONTH_COUNT M
JOIN RENTAL_COUNT R ON R.CAR_ID = M.CAR_ID
ORDER BY M.MONTH, M.CAR_ID DESC;