-- 코드를 작성해주세요
-- EMP_NO으로 GROUP BY
WITH GRADE AS(
    SELECT EMP_NO, SUM(SCORE) SCORE FROM HR_GRADE
    GROUP BY EMP_NO
    ORDER BY SCORE DESC
    )
    
SELECT G.SCORE, H.EMP_NO, H.EMP_NAME, H.POSITION, H.EMAIL FROM GRADE G
JOIN HR_EMPLOYEES H ON H.EMP_NO = G.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;